// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnbzmvdalfmzueuigirx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uYnptdmRhbGZtenVldWlnaXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDk0NjYsImV4cCI6MjA3MTk4NTQ2Nn0.VYoLPFC4neVF81CpZGTHIi1cjtubFiqUsD-EcBA9cEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});